### ISSUE TITLE
Secure Domain - Internal Auth - Not Authenticating

### ISSUE THREAD

**Issue by daaaaan** [jitsi/docker-jitsi-meet#216]
Having followed the docs for deployment of secure domain with internal authentication. 

The only changes I've really made are as follows : 

```

HTTP_PORT=80
HTTPS_PORT=443
PUBLIC_URL="https://video.fqdn.live" << with corresponding lets encrypt enabled
DOCKER_HOST_ADDRESS=167.172*****
ENABLE_AUTH=1
ENABLE_GUESTS=1
AUTH_TYPE=internal

```

Then I've run 
```

docker-compose exec prosody /bin/bash
prosodyctl --config /config/prosody.cfg.lua register username meet.jitsi passsword

```

Then headed to video.fqdn.live/test, which was working without auth, and hit the "Password Required" dialog. 

I've tried 

```
username:password
username@meet.jitsi:password

```

So far no joy, console shows : 

```

CONNECTION FAILED: connection.passwordRequired

```

Prosody logs show : 

```

New BOSH session, assigned it sid '7e81b464-8d6a-424e-b0b2-8fbc0cbe114d'

```

But nothing further after failed logon. 

I've rebuilt the docker images and volumes a few times, wiped the config folder etc 

Any help appreciated. 🤷‍♂

**Comment by daaaaan** [comment]
Had a look a bit further down the prosody logs and this is hiding up there : 

```

 mv: cannot stat '/config/data/*.crt': No such file or directory
prosody_1  | mv: cannot stat '/config/data/*.key': No such file or directory
prosody_1  | [cont-init.d] 10-config: exited 0.

```
Likely root cause?

**Comment by saghul** [comment]
Did you change your .env configuration after starting contaainers? If so you must detroy your CONFIG directory and start again so it gets recreated.

**Comment by daaaaan** [comment]
> Did you change your .env configuration after starting contaainers? If so you must detroy your CONFIG directory and start again so it gets recreated.

Yes, this has been done. Also with a docker-compose down --rmi="all" --volumes as well to get rid of any dangling volume files.

**Comment by saghul** [comment]
Can you paste the generated prosody configuration?

**Comment by daaaaan** [comment]
This is fixed with PR #228 

Its a documentation issue. Wrong Prosody command.

**Comment by sukubo** [comment]
No of this fixes do it... still cant add user y prosodyctl... another cuestion, some can put an own valid signe certificate, not a let's encrypt?

**Comment by amazzoccone** [comment]
Same here :confused: I cannot make it work following [documentation](https://github.com/jitsi/jicofo#secure-domain).

**Comment by blitzdesigner** [comment]
I have to second that issue, I did everything by the book and it all works w/o authentification.
But as soon I enable auth, delete old config-dir, startup the compose and enter the prosody container to register new user with
`prosodyctl --config /config/prosody.cfg.lua register username meet.jitsi password`
I get 
`Error: Account creation/modification not supported.`

The creation of rooms still works w/o auth though.

I digged around in the prosody config and discovered, that the virtual host "meet.jitsi" has set 
`authentication = "anonymous``.
As soon I change that to "internal_plain" I am able to register the user an get asked to auth when I want to create a room. BUT, I also get asked for a pass when I want to invite other users to that room, so the anon-part does not work.

Is is possible, that running jitsi in Docker, its by design not possible to use the guest-feauture with just one public URL? 

any help appreciated!

**Comment by KrishanBhasin** [comment]
> Error: Account creation/modification not supported

I had this for a while, you need to dive into your `.env` file and make sure

```
ENABLE_AUTH=1
```
is uncommented (remove the `#` before it)

**Comment by MikesItServices** [comment]
any luck getting this running, I'm in the same boat.

**Comment by Lukas1818** [comment]
same problem to
