### ISSUE TITLE
LDAP does not even try

### ISSUE THREAD

**Issue by Expeto** [jitsi/docker-jitsi-meet#285]
Hello,

I'm trying to integrate my jitsi install in ldap, but for some reason jitsi does not even try to talk with DC.

To reproduce 
  ```
cd /tmp/
rm -rf /root/.jitsi-meet-cfg/
git clone https://github.com/jitsi/docker-jitsi-meet
cd docker-jitsi-meet/
cp env.example .env
echo "ENABLE_AUTH=1" >> .env 
echo "AUTH_TYPE=ldap" >> .env 
echo "LDAP_AUTH_METHOD=bind" >> .env 
echo "LDAP_URL=ldaps://10.7.xx.xx/" >> .env 
echo "LDAP_BASE=DC=some,DC=domain" >> .env 
echo "LDAP_BINDPW= mysecret" >> .env 
```
In another terminal 
` tcpdump -i ens160 -n host 10.7.XX.XX`

Then I run a docker compose up , tcpdump sees nothing.
I enter a room it asks password, I enter a username and password. Login popup gets stuck at "Connecting",  tcp dump caches nothing. For some reason system does not even try to talk with AD.

I get a shell in prosody container and run :
```
root@a34454ec823c:/# testsaslauthd -u asd -p asd
0: NO "authentication failed"
```

Now there is lots of packages flow through tcpdump. 

Also when I give a docker-compose down, I also see few packages in tcpdump. 

Any idea?

**Comment by m4tze** [comment]
You should set your bind dn?

**Comment by Expeto** [comment]
```
root@8a53ea5490de:/# cat /etc/saslauthd.conf 

ldap_servers: ldaps://10.7.131.11/
ldap_search_base: DC=some,DC=domain

ldap_filter: uid=%u
ldap_version: 3
ldap_auth_method: bind

```

Added the BINDDN still the same , no packages in tcpdump.

**Comment by Expeto** [comment]
```
root@8a53ea5490de:/# cat /etc/saslauthd.conf 

ldap_servers: ldaps://10.7.xx.xx/
ldap_search_base: DC=some,DC=domain

ldap_filter: uid=%u
ldap_version: 3
ldap_auth_method: bind

```

Added the BINDDN still the same , no packages in tcpdump.

**Comment by saghul** [comment]
Please rebuild the images and try again, I believe this is fixed on master.

**Comment by Expeto** [comment]
Thanks, that did it.

**Comment by ginkel** [comment]
@saghul Also stumbled across this issue. As I'm getting the images from Docker Hub, do you have an indication when an updated image will be published?

**Comment by saghul** [comment]
I’ll try to publish new images today.

**Comment by saghul** [comment]
Done. 4101-2 are up.

**Comment by rwaeselynck** [comment]
Hi, I hope I'm not doing a huge mistake, but for me, even with the lattest version, I still don't have the BIND DN in saslauthd.conf:
`ldap_servers: ldap://192.168.1.254
ldap_search_base: dc=ldap,dc=;my-own-server,dc=com

ldap_filter: uid=%u
ldap_version: 3
ldap_auth_method: bind
`
though wy .env file set a value for it... Any clues about what's going on ?

**Comment by saghul** [comment]
Are you sure you’re using the latest images? Remove the config volume before running them.

**Comment by bkraul** [comment]
I am using the latest image and it is still happening. Setting `AUTH_TYPE=ldap` (with all BIND and other pertaining information) has absolutely no effect. Every one gets moderator rights, even when `ENABLE_AUTH=1` is set. I have removed all config volumesand re-pulled the latest image, to no avail.

I see that the lua file in /conf.d still sets the authentication method to `internal_plain`. Previously, this would be set to ldap.

Which image could I get from the archive tags that does not have the changes to ldap handling?

**Comment by bkraul** [comment]
I see in the prosody folder that there is a new env var called `ENABLE_LDAP_AUTH`. Can someone tell me what's going on? what happens to `AUTH_TYPE=ldap` is this why ldap is not being used at all by prosody? I have put both env vars in the compose, and still no ldap authentication takes place.

**Comment by bkraul** [comment]
Also, something really weird is going on with the docker pulls. I removed all jitsi images from my system, and re-pulled all images from `jitsi/..`, and what I am getting is this:
```
jitsi/jvb                                                 latest              fd8201652975        5 days ago          276MB
jitsi/jicofo                                              latest              773ffe263260        5 days ago          277MB
jitsi/prosody                                             latest              5734ef478ff3        5 days ago          256MB
jitsi/web                                                 latest              7afd18fc710a        5 days ago          266MB
```
But I can see that the latest `prosody` image has a hash of `1237cf22a228`, which obviously is not the same, and I don't even see the hash that I have in the list of archived tags anymore...

**Comment by bkraul** [comment]
Can anyone please help? I have gone back to even tag 3936 (7 months ago), deleted all config volumes, to no avail. I am certain the LDAP data that is on my env vars is correct, because this was working perfectly last week. I am puzzled by the fact that I have `ENABLE_AUTH=1` yet it still grants moderator rights to anyone who enters the room.

**Comment by bkraul** [comment]
I can verify that LDAP auth works **ONLY** if `ENABLE_GUESTS=0` in both web and prosody. I believe this to be a bug, since, as mentioned, the previous behavior was authentication was only expected until a moderator created the room, allowing subsequent guests to access without an account.

**Comment by bkraul** [comment]
**SOLVED:** For those who went through all this mess. My problem was that I had `ENABLE_AUTH=1, ENABLE_GUESTS=1` on `web` and on `prosody`, but I had `ENABLE_AUTH=0` on **jicofo**. This is why the behavior was happening. After I removed all config volumes and set `ENABLE_AUTH=1` on jicofo, LDAP auth works correctly.

I am still curious about the new `ENABLE_LDAP_AUTH` var that I am seeing in the repo. Is LDAP going to change again?

**Comment by sirrus** [comment]
@bkraul it's not the same. Disabling guest access does not change anythin.

**Comment by ramonjoaquim** [comment]
> **SOLVED:** For those who went through all this mess. My problem was that I had `ENABLE_AUTH=1, ENABLE_GUESTS=1` on `web` and on `prosody`, but I had `ENABLE_AUTH=0` on **jicofo**. This is why the behavior was happening. After I removed all config volumes and set `ENABLE_AUTH=1` on jicofo, LDAP auth works correctly.
> 
> I am still curious about the new `ENABLE_LDAP_AUTH` var that I am seeing in the repo. Is LDAP going to change again?

thanks! this help me a lot

**Comment by sirrus** [comment]
Solved for team-container too...
https://github.com/ct-Open-Source/team-container/pull/39
