### ISSUE TITLE
Special chars and spaces in room names

### ISSUE THREAD

**Issue by hannob** [jitsi/docker-jitsi-meet#353]
When I use the jitsi docker-compose setup and try to create a room name with a space in it or a specia char (e.g. äöü) then I get a 404 error.

This can be quite confusing to users. At the very least one would expect a useful error message (i.e. telling the user which characters are allowed in a channel name).

The instance on meet.jit.si does not have these problems. Spaces seem to get automatically removed from room names and special chars just work.

**Comment by retani** [comment]
Check if you are using the latest version. I had this problem last week but it got fixed in the current version. Docker Tag is "4101-2"

**Comment by freechelmi** [comment]
Still happening with today latest images. But not a big issue IMO

**Comment by saghul** [comment]
Should've been fixed with the latest (or latest -1) images. Please holler if not.
