### ISSUE TITLE
docker-jitsi-meet jibri container - jibri tells ffmpeg to listen to plug:bsnoop, .asoundrc has dsnoop

### ISSUE THREAD

**Issue by elbow** [jitsi/docker-jitsi-meet#479]
I've built my own jibri docker image, since I needed to change some things in jibri to deal with the SSL cert problems.

My Makefile at the top of the project is asking for JITSI_RELEASE stable.

I see that base/Dockerfile has "ARG JITSI_RELEASE=stable" too...?

My revised Dockerfile is the standard one, except at the end I COPY my locally built jibri.jar into /opt/jitsi/jibri/jibri.jar

When jibri in my jibri docker container starts ffmpeg, it uses the command line

```
ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i plug:bsnoop -acodec aac -strict -2 -ar 44100 -c:v libx264 -preset veryfast -profile:v main -level 3.1 -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f mp4 /config/recordings/xxzjnmkfonlrefyy/xyz_2020-04-18-12-06-26.mp4
```
audio input from plug:bsnoop.

This fails :- 

```
2020-04-18 12:06:29.629 INFO: [54] ffmpeg.call() ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bsnoop
2020-04-18 12:06:29.629 INFO: [54] ffmpeg.call() [alsa @ 0x56223f736e80] cannot open audio device plug:bsnoop (No such file or directory)
```

~jibri/.asoundrc in the container has:

```
# playback PCM device: using loopback subdevice 0,0
pcm.amix {
  type dmix
  ipc_key 219345
  slave.pcm "hw:Loopback,0,0"
}

# capture PCM device: using loopback subdevice 0,1
pcm.asnoop {
  type dsnoop
  ipc_key 219346
  slave.pcm "hw:Loopback,0,1"
}

# duplex device combining our PCM devices defined above
pcm.aduplex {
  type asym
  playback.pcm "amix"
  capture.pcm "asnoop"
}

# ------------------------------------------------------
# for jack alsa_in and alsa_out: looped-back signal at other ends
pcm.ploop {
  type plug
  slave.pcm "hw:Loopback,1,1"
}

pcm.cloop {
  type dsnoop
  ipc_key 219348
  slave.pcm "hw:Loopback,1,0"
}

# ------------------------------------------------------
# default device

pcm.!default {
  type plug
  slave.pcm "aduplex"
}
```

This came from the standard stable install.  But of course my jibri.jar was built from master on github so it looks like there is an incompatibility ... ?

I'd appreciate any help from those who know the product better than this newbie.

**Comment by netaskd** [comment]
It has been changed in https://github.com/jitsi/jibri/commit/5a71969bd770dca7c54cdf6a14567c902797a377
and
https://github.com/jitsi/jibri/commit/600d4feeb85f280184e18b063ba81e7757d27c77

**Comment by cupuyc** [comment]
Having the same issue. I've put fresh `.asoundrc` but still the same error.

**Comment by kavirajan2** [comment]
Faced the same issue fixed by replacing the .asoundrc file  (/home/jibri/.asoundrc) with the below content and restart the Jibri service.

https://raw.githubusercontent.com/jitsi/jibri/master/resources/debian-package/etc/jitsi/jibri/asoundrc

**Comment by cupuyc** [comment]
I kind of fixed that by reverting change in `Commands.kt` 
from `"-i", "plug:bsnoop",`
to   `"-i", "hw:0,1,0",`
as it was in the original release.

**Comment by hypnotic-frog** [comment]
For some some reason this is still not working.
I'm using Docker containers compiled from the unstable build and it gives me the same error 

`2020-07-24 22:50:41.556 INFO: [58] ffmpeg.call() [alsa @ 0x55b4a5f433e0] cannot open audio device plug:bsnoop (No such file or directory)`

The ~jibri/.asoundrc file seems to be correct. But, no results. Somebody has a solution for this? Thanks in advance.

**Comment by DonxDaniyar** [comment]
Hi guys! I have the same problem! I have 3 instances when i run 1 instance it works. If i enable second jibri instance it fails with `Last output line: plug:bsnoop: Input/output error` Any solution?

**Comment by umitgri** [comment]
Hi there. I have the same problem. Did others install from https://hub.docker.com/r/jitsi/jibri or from jitsi-meet-docker https://github.com/jitsi/docker-jitsi-meet

I am using image from https://hub.docker.com/r/jitsi/jibri 

What i am thinking to switch jitsi-meet-docker and give it a try...

**Comment by umitgri** [comment]
I have found the exact problem in my case;
pcm.bsnoop {
  type dsnoop
  ipc_key 219348
  slave.pcm "hw:Loopback,1,0"
}
When i set up pcm.bsnoop slave.pcm value to other Loopback i.e. Loopback_1,  Loopback_2 etc jibri docker instance is giving mpeg error mentioned above.

But any other slave.pcm parameters works fine with other Loopback values (1,2,3 etc)

So that i that because i count not give any value to bsnoop slave.pcm value other than Loopback, i could not run multiple Jibri instances concurently. Because when i do this first intance will use Loopback and others will not able to use it. 

I have no solution for that for now.

**Comment by netaskd** [comment]
@umitgri you could check [this](https://github.com/netaskd/docker-jitsi-meet/blob/dev/jibri/rootfs/etc/cont-init.d/20-detect-free-cards) file to get an idea how to do it.
