### ISSUE TITLE
Etherpad menu has no icons/ symbols with newest commit

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#540]
With new release (https://github.com/jitsi/docker-jitsi-meet/tree/stable-4548) etherpad has a dumb menu.

Function is given though.

**Comment by saghul** [comment]
Can you share an screenshot of what you see?

**Comment by tele-tom** [comment]
It's because fonts can't be downloaded:
Here's the firefox console log. Again we have CORS errors (mouse over event), too but that's another thing.
There's also an error that wss:// connection can't be established. (wss://my.domain.de/etherpad/socket.io...). Is that mandatory?

```
2020-05-02T18:52:06.296Z [modules/UI/videolayout/SmallVideo.js] <updateView>:  Displaying blackness-with-name for 90e1d831, data: [{"isCurrentlyOnLargeVideo":true,"isHovered":false,"isAudioOnly":false,"tileViewEnabled":false,"isVideoPlayable":true,"hasVideo":true,"connectionStatus":null,"videoStream":true,"isVideoMuted":false,"videoStreamMuted":false}] Logger.js:154:22
downloadable font: download failed (font-family: "Quicksand" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/Quicksand-Medium.ttf
downloadable font: download failed (font-family: "Quicksand" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/Quicksand-Bold.ttf
downloadable font: download failed (font-family: "fontawesome-etherpad" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://my.domain.de/static/font/fontawesome-etherpad.woff?2
downloadable font: download failed (font-family: "fontawesome-etherpad" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://my.domain.de/static/font/fontawesome-etherpad.ttf?2
downloadable font: no supported format found (font-family: "fontawesome-etherpad" style:normal weight:400 stretch:100 src index:4) source: (end of source list)
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/ require-kernel.js:1:1962
2020-05-02T18:52:07.349Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: SecurityError: Permission denied to access property "onmousemove" on cross-origin object Script: https://my.domain.de/libs/app.bundle.min.js?v=4074 Line: 152 Column: 0 StackTrace:  DOMException: "Permission denied to access property "onmousemove" on cross-origin object" Logger.js:154:22
SecurityError: Permission denied to access property "onmousemove" on cross-origin object app.bundle.min.js:152
Couldn't find translation key pad.settings.about html10n.js:1:8258
Couldn't find translation key pad.settings.poweredBy html10n.js:1:8258
Firefox kann keine Verbindung zu dem Server unter wss://my.domain.de/etherpad/socket.io/?EIO=3&transport=websocket&sid=mB4WB69NbI8E-7UaAAAC aufbauen. socket.io.js:7:23187
Object { type: "CLIENT_VARS", data: {…} }
pad.js:3:5233
downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/Roboto-Regular.ttf
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/ d90fa0050e734daf895fd6b564c04770:9:1962
downloadable font: download failed (font-family: "RobotoMono" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/RobotoMono-Regular.ttf
downloadable font: download failed (font-family: "Quicksand" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/Quicksand-Medium.ttf
downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://my.domain.de/static/font/Roboto-Regular.ttf
2020-05-02T18:52:08.068Z [features/base/storage] <persistState>:  redux state persisted. c1e11337ae5ff8c0e99a9426813fd190 -> e8a38f89f6cc213e5da4e3bf312acd8a Logger.js:154:22
```

**Comment by infisinfis** [comment]
Same issue:

![2020-05-06 10_05_30-Window](https://user-images.githubusercontent.com/50703791/81151644-7c77ca80-8f81-11ea-8d0f-f8aa6c51cced.jpg)

**Comment by geekyayush** [comment]
Well, I'm having the same issue :/

**Comment by yetianyes** [comment]
i have this issue too

**Comment by psymin** [comment]
This resolves the issue for me.

Add this to the nginx config just below your entry for Etherpad-lite.

    location ^~ /static/ {
        root /path/to/etherpad-lite/src/static;
    }

**Comment by psymin** [comment]
This resolved it for me on Ubuntu 20.04

sudo ln -s /path/to/etherpad-lite/src/static/font /usr/share/jitsi-meet/static/

**Comment by andreas-bulling** [comment]
same for me (Ubuntu 18.04)

**Comment by glehuic** [comment]
same for me debian 10 and install of etherpad on a separate CT, so no symbolic link...

**Comment by psymin** [comment]
@glehuic Try copying the etherpad-lite/src/static/font directory to the location that is being served by the webserver hosting jitsi-meet (the "static" subdir)

**Comment by glehuic** [comment]
yes i will try that thanks

**Comment by tele-tom** [comment]
In the docker setup a symlink is problematic, too.
So I copied the stuff into the web container... I hope this will be fixed soon...

**Comment by glehuic** [comment]
![image](https://user-images.githubusercontent.com/43320397/81610759-ed7c0f80-93d1-11ea-89f3-7135da6b8cab.png)

the cp of font to to the static jitsi works fine

**Comment by andreas-bulling** [comment]
But the problem reoccurs for me when using plugins like `ep_superscript`

**Comment by smeagel73** [comment]
@glehuic: can u explain what u have copied?

**Comment by vintas** [comment]
Issue fixed in etherpad 1.8.4 as per https://github.com/ether/etherpad-lite/issues/3956
Tried it and it works on my jitsi.
![image](https://user-images.githubusercontent.com/17967770/82169784-335c3a80-98e0-11ea-89c9-89567f825391.png)

Issue also mentioned in #572

**Comment by saghul** [comment]
Closing in favor of #572

**Comment by tele-tom** [comment]
For me it still doesn't work. :(
Browser tries to load e.g.
`https://meet.mydom.de/static/font/Quicksand-Medium.ttf`
and gets 404.
When I use the URL
`https://meet.mydom.de/etherpad/static/font/Quicksand-Medium.ttf`
manually then the font gets downloaded.
What am I missing? I tried last stable release and modified the etherpad Dockerfile to use version 1.8.4 and I also used latest docker-jitsi-meet where it already uses 1.8.4.
What do you need to help me?

**Comment by vintas** [comment]
@tele-tom Could you try rebuilding the etherpad image and tagging it as latest?

These steps worked for me: https://github.com/jitsi/docker-jitsi-meet/pull/572#issuecomment-629920372

**Comment by tele-tom** [comment]
etherpad.yml uses
`jitsi/etherpad:stable-4548-1` so what should this do for me?

**Comment by glehuic** [comment]
@smeagel73
i done this :
scp from server1 etherpad /static/font of etherpad to the server 2 jitsi /usr/share/jitsi-meet/static/
